# Generated by Django 6.1.1 on 2026-09-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(
                default=True,
                help_text="Unapproved users cannot sign in. Self-registered doctors await administrator approval.",
            ),
        ),
    ]
