# Generated by Django 6.1.1 on 2026-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.BigIntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "MALE"),
                            ("female", "FEMALE"),
                            ("other", "OTHER"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=11)),
            ],
        ),
    ]
