# Generated by Django 6.1.1 on 2026-09-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
